// const lockfile = require('@yarnpkg/lockfile');
const assert = require('assert');
const { updatePackages } = require('../index');

// const parseYarnLock = (content) => lockfile.parse(content).object;

describe('Library', () => {
  it('should not update fixed version', async () => {
    const yarnLock = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


library@2.0.0:
  version "2.0.0"
  resolved "https://example.net/library@2.0.0"

library@>=1.0.0:
  version "2.0.0"
  resolved "https://example.net/library@2.0.0"
`;
    const updated = await updatePackages(yarnLock);

    assert.strictEqual(updated, yarnLock, updated);
  });
});
